apiVersion: v1
kind: Service
metadata:
  name: kr8sswordz
  labels:
    app: kr8sswordz
spec:
  ports:
    - port: 80
      targetPort: 3002
  selector:
    app: kr8sswordz
    tier: kr8sswordz
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kr8sswordz
  labels:
    app: kr8sswordz
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kr8sswordz
        tier: kr8sswordz
    spec:
      containers:
      - image: $KR8SS_IMG
        name: kr8sswordz
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
          name: kr8sswordz
